#!/bin/bash
#
# DEFINES - global definitions
#
# PROJECT: MUTINY Tahiti's websites
#
# Copyright (C) 1995-2015 - Franck Porcher, Ph.D 
# www.franckys.com
# Tous droits réservés
# All rights reserved


#----------------------------------------
# APPLICATION MODULES
#----------------------------------------
# Modules Arborescence
declare -A MODULES
MODULES[root]='mutiny'
MODULES[mutiny]='wordpress store cgm'

#----------------------------------------
# WEB SERVER CREDENTIALS
#----------------------------------------
WWWUID='www-data'
WWWGID='www-data'

#----------------------------------------
# GIT STUFF 
#----------------------------------------
GIT_URL="ssh://git@github.com/franckporcher"

# Git Modules
declare -A INITIAL_RELEASE
declare -A CURRENT_RELEASE

# moduleName > ReposName:BranchName:InstallDir
# InstallDir shoudl be either an absolute path,
# or a relative path from <topinstalldir>/libexec
# (from where all the scripts run)
INITIAL_RELEASE[mutiny]="    mutiny-www      stable-v1.0            ~${WWWUID}/mutiny"
INITIAL_RELEASE[wordpress]=" mutiny-www-wp   init-4.1.1-v1.0        ~${WWWUID}/mutiny"
INITIAL_RELEASE[store]="     mutiny-www-ps   init-1.6.0.14-v1.0     ~${WWWUID}/mutiny/store"
INITIAL_RELEASE[cgm]="       mutiny-www-cgm  stable-v1.0            ~${WWWUID}/mutiny/cgm"


#----------------------------------------
# MYSQL DB CREDENTIALS
#----------------------------------------
#SQL_DBSERVER=devsql.mutinytahiti.com
SQL_DBSERVER='mutiny-staging-rds.cfwvxsax91fg.us-east-1.rds.amazonaws.com'

SQL_ROOT=root
SQL_DBADMIN='mutiny_db_admin'
SQL_DBADMIN_PWD='AmantesIslaUnidos'

SQL_PSDB=psmutiny
SQL_WPDB=wpmutiny


#----------------------------------------
# INSTALLATION HELPERS
#----------------------------------------
BOOTSTRAP_MODULE='bootstrap.sh'
INSTALL_MODULE='install_module.sh'
UPDATE_MODULE='update_module.sh'

