#!/bin/bash
#
# DEFINES - global definitions
#
# PROJECT: MUTINY Tahiti's websites
#
# Copyright (C) 2014-2015 - Franck Porcher, Ph.D 
# www.franckys.com
# Tous droits réservés
# All rights reserved

#----------------------------------------
# LEAVE IT HERE
#----------------------------------------
# Extract a piece of config from a file
function getconf () {
    local file="$1"
    local regex="$2"

    #echo "[GETCONF]  file:($file)"
    #echo "          regex:($regex)"

    if [ -e "${file}" ]
    then
        cat "${file}" | $PERL -ne "print \"\$1\" if m|${regex}|"
    else
        echo "file_not_found_${file}"
    fi
}

#----------------------------------------
# MYSQL DB CREDENTIALS 1/2
#----------------------------------------
SQL_ROOT='root'
SQL_DBADMIN='mutiny_db_admin'
SQL_DBADMIN_PWD='AmantesIslaUnidos'

# Prestashop
SQL_PSDB=psmutiny

# Wordpress
SQL_WPDB=wpmutiny

export SQL_ROOT SQL_DBADMIN SQL_DBADMIN_PWD SQL_PSDB SQL_WPDB


#----------------------------------------
# BOOTSTRAP CUSTOM DEFS FROM :
#   (in thar order)
#   . Machine's hostname
#   . Machine's osname
#   Use 'default' is no match
#----------------------------------------
HOSTNAME="$(hostname)"
OSNAME="$(uname -o 2> /dev/null || uname -s 2> /dev/null)"  # -> Darwin on Mac, Linux on Linux
OSNAME="${OSNAME,,*}"                                       # Small caps => darwin linux freebsd
if   [ -e "HOST.${HOSTNAME}" ]
then
    CUSTOMDEFS="HOST.${HOSTNAME}"
elif [ -e "HOST.${OSNAME}" ]
    CUSTOMDEFS="HOST.${OSNAME}"
else
    CUSTOMDEFS="HOST.default"
fi

if [ -e  "${CUSTOMDEFS}" ]
then
    "${CUSTOMDEFS}"
fi

export HOSTNAME OSNAME CUSTOMDEFS


#----------------------------------------
# WEB SERVER CREDENTIALS
#----------------------------------------
WWWUID="${APACHE_RUN_USER}"
WWWGID="${APACHE_RUN_GROUP}"
WWWHOME=~"${APACHE_RUN_GROUP}"
export WWWUID WWWGID WWWHOME


#----------------------------------------
# APPLICATION MODULES
#----------------------------------------
# Modules Arborescence
unset IS_MODULE
declare -A IS_MODULE
IS_MODULE[root]=1
IS_MODULE[mutiny]=1
IS_MODULE[wordpress]=1
IS_MODULE[store]=1
IS_MODULE[cgm]=1
IS_MODULE[perltrace]=1
IS_MODULE[perlerror]=1
IS_MODULE[perlmuffinmc]=1

unset MODULES
declare -A MODULES
MODULES[root]='mutiny'
MODULES[mutiny]='wordpress store cgm'
MODULES[wordpress]=''
MODULES[store]=''
MODULES[cgm]='perltrace perlerror perlmuffinmc'
MODULES[perltrace]=''
MODULES[perlerror]=''
MODULES[perlmuffinmc]=''

unset PARENT_MODULE
declare -A PARENT_MODULE
PARENT_MODULE[mutiny]=''
PARENT_MODULE[wordpress]='mutiny'
PARENT_MODULE[store]='mutiny'
PARENT_MODULE[cgm]='mutiny'
PARENT_MODULE[perltrace]='cgm'
PARENT_MODULE[perlerror]='cgm'
PARENT_MODULE[perlmuffinmc]='cgm'

#----------------------------------------
# APP GIT MODULES 
#----------------------------------------
#GIT_URL="ssh://git@github.com/franckporcher"
#GIT_URL="https://git@github.com/franckporcher"
GIT_URL="git://github.com/franckporcher"
export GIT_URL

# Git Modules
unset  INITIAL_RELEASE
unset  CURRENT_RELEASE
declare -A INITIAL_RELEASE
declare -A CURRENT_RELEASE

#      RELEASE[ MODULE_NAME ] =         GIT-REPOS_NAME          BRANCH_NAME            MODULE_DIR                      INSTALL_DIRAUXDIR
#
# InstallDir should be either an absolute path,
# or a relative path from <topinstalldir>/libexec
# (from where all the scripts run)
INITIAL_RELEASE[mutiny]="               mutiny-www              stable-v1.0            ${WWW_INSTALLDIR}"
INITIAL_RELEASE[wordpress]="            mutiny-www-wp           init-4.1.1-v1.0        ${WWW_INSTALLDIR}/wordpress     ${WWW_INSTALLDIR}"
INITIAL_RELEASE[store]="                mutiny-www-ps           init-1.6.0.14-v1.0     ${WWW_INSTALLDIR}/store"
INITIAL_RELEASE[cgm]="                  mutiny-www-cgm          stable-v1.0            ${WWW_INSTALLDIR}/cgm"
INITIAL_RELEASE[perltrace]="            perl5-Franckys-Trace    v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysTrace"
INITIAL_RELEASE[perlerror]="            perl5-Franckys-Error    v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysError"
INITIAL_RELEASE[perlmuffinmc]="         perl5-Franckys-MuffinMC v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysMuffinMC"

CURRENT_RELEASE[mutiny]="               mutiny-www              stable-v1.0            ${WWW_INSTALLDIR}"
CURRENT_RELEASE[wordpress]="            mutiny-www-wp           init-4.1.1-v1.0        ${WWW_INSTALLDIR}/wordpress     ${WWW_INSTALLDIR}"
CURRENT_RELEASE[store]="                mutiny-www-ps           init-1.6.0.14-v1.0     ${WWW_INSTALLDIR}/store"
CURRENT_RELEASE[cgm]="                  mutiny-www-cgm          stable-v1.0            ${WWW_INSTALLDIR}/cgm"
CURRENT_RELEASE[perltrace]="            perl5-Franckys-Trace    v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysTrace"
CURRENT_RELEASE[perlerror]="            perl5-Franckys-Error    v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysError"
CURRENT_RELEASE[perlmuffinmc]="         perl5-Franckys-MuffinMC v0.11-stable           ${WWW_INSTALLDIR}/cgm/modperl/FranckysMuffinMC"


#----------------------------------------
# MYSQL DB CREDENTIALS 2/2
#----------------------------------------
#SQL_DBSERVER=devsql.mutinytahiti.com
SQL_DBSERVER="${DBSERVER}"

export SQL_DBSERVER


#----------------------------------------
# INSTALLATION HELPERS
#----------------------------------------
BOOTSTRAP_MODULE='bootstrap.sh'
INSTALL_MODULE='install_module.sh'
UPDATE_MODULE='update_module.sh'

export BOOTSTRAP_MODULE INSTALL_MODULE UPDATE_MODULE

